name: LLobby
version: '1.0.0'
main: top.syshub.lLobby.LLobby
api-version: '1.20'
authors:
  - Dainsleif
description: A lite lobby plugin.
website: mc.syshub.top
commands:
  llobby: {}
  llobbyadmin:
    permission: "llobby.admin"
permissions:
  llobby.admin:
    default: op
