name: LLobby
version: '${version}'
main: top.syshub.lLobby.LLobby
api-version: '1.21'
authors:
  - Dainsleif
description: A lite lobby plugin.
website: mc.syshub.top
depend:
  - ProtocolLib
softdepend:
  - PlaceholderAPI
commands:
  llobby: {}
  llobbyadmin:
    permission: "llobby.admin"
permissions:
  llobby.admin:
    default: op
